AWSTemplateFormatVersion: "2010-09-09"
Description: >
  This CloudFormation template creates a role assumed by CloudFormation
  during CRUDL operations to mutate resources on behalf of the customer.

Resources:
  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      MaxSessionDuration: 8400
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: resources.cloudformation.amazonaws.com
            Action: sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: ResourceTypePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                - "directconnect:DescribeConnections"
                - "directconnect:DescribeDirectConnectGatewayAssociations"
                - "directconnect:DescribeDirectConnectGatewayAttachments"
                - "directconnect:DescribeDirectConnectGateways"
                - "directconnect:DescribeVirtualGateways"
                - "directconnect:DescribeVirtualInterfaces"
                - "ec2:CreateTags"
                - "ec2:DeleteNetworkInsightsAnalysis"
                - "ec2:DeleteTags"
                - "ec2:DescribeAvailabilityZones"
                - "ec2:DescribeCustomerGateways"
                - "ec2:DescribeInstances"
                - "ec2:DescribeInternetGateways"
                - "ec2:DescribeManagedPrefixLists"
                - "ec2:DescribeNatGateways"
                - "ec2:DescribeNetworkAcls"
                - "ec2:DescribeNetworkInsightsAnalyses"
                - "ec2:DescribeNetworkInterfaces"
                - "ec2:DescribePrefixLists"
                - "ec2:DescribeRegions"
                - "ec2:DescribeRouteTables"
                - "ec2:DescribeSecurityGroups"
                - "ec2:DescribeSubnets"
                - "ec2:DescribeTransitGatewayAttachments"
                - "ec2:DescribeTransitGatewayPeeringAttachments"
                - "ec2:DescribeTransitGatewayRouteTables"
                - "ec2:DescribeTransitGatewayVpcAttachments"
                - "ec2:DescribeTransitGateways"
                - "ec2:DescribeVpcEndpointServiceConfigurations"
                - "ec2:DescribeVpcEndpoints"
                - "ec2:DescribeVpcPeeringConnections"
                - "ec2:DescribeVpcs"
                - "ec2:DescribeVpnConnections"
                - "ec2:DescribeVpnGateways"
                - "ec2:GetManagedPrefixListEntries"
                - "ec2:GetTransitGatewayRouteTablePropagations"
                - "ec2:SearchTransitGatewayRoutes"
                - "ec2:StartNetworkInsightsAnalysis"
                - "elasticloadbalancing:DescribeListeners"
                - "elasticloadbalancing:DescribeLoadBalancerAttributes"
                - "elasticloadbalancing:DescribeLoadBalancers"
                - "elasticloadbalancing:DescribeRules"
                - "elasticloadbalancing:DescribeTags"
                - "elasticloadbalancing:DescribeTargetGroups"
                - "elasticloadbalancing:DescribeTargetHealth"
                - "tiros:CreateQuery"
                - "tiros:GetQueryAnswer"
                - "tiros:GetQueryExplanation"
                Resource: "*"
Outputs:
  ExecutionRoleArn:
    Value:
      Fn::GetAtt: ExecutionRole.Arn
